### ISSUE TITLE
realm settings - Frontend URL

### ISSUE THREAD

**Issue by phac008** [crossplane-contrib/provider-keycloak#105]
hi!

I need to set parameter "Frontend URL" for my realm - didn't find any hint how to set this up?

**Comment by Breee** [comment]
- I don't see that directly in https://registry.terraform.io/providers/mrparkers/keycloak/latest/docs/resources/realm 
- Only a field called `attributes` which maybe can hold that information?
- I also don't really find it in the API: https://www.keycloak.org/docs-api/22.0.1/rest-api/index.html#RealmRepresentation (except i missed it)  
- We Probably need to set the frontendURL and then look that what the API returns when fetching the realm itself

**Comment by phac008** [comment]
good hints - I tried: setting frontentURL in UI and realm export afterwards show that this parameter is saved in attributes field - I will try this and give feedback.

**Comment by phac008** [comment]
```

apiVersion: realm.keycloak.crossplane.io/v1alpha1
kind: Realm
metadata:
  name: ...
spec:
  forProvider:
   ...
    attributes:
      frontendUrl: https://...
```

      
works for me, thank you
