### ISSUE TITLE
Add an option to extend list of group members

### ISSUE THREAD

**Issue by vladimirblahoz** [crossplane-contrib/provider-keycloak#134]
Hi,
I wasn't able to find any way of adding another user to an existing group with already defined [memberships](https://marketplace.upbound.io/providers/crossplane-contrib/provider-keycloak/v1.0.0/resources/group.keycloak.crossplane.io/Memberships/v1alpha1) resource. New memberships only overwrite the list of members for a group.
This way we cannot contribute to a single group with users from different projects.
I was expecting something similar to an **exhaustive** property which is present in **group roles** resource or **user roles** resource.

**Comment by Breee** [comment]
Example?

**Comment by vladimirblahoz** [comment]
```
apiVersion: user.keycloak.crossplane.io/v1alpha1
kind: User
metadata:
  name: user
spec:
  providerConfigRef:
    name: keycloak-default
  forProvider:
    enabled: true
    realmId: acmecorp-00001
    username: user
    initialPassword:
      - temporary: false
        valueSecretRef:
          key: credentials
          name: initial-user-global-acmecorp-00001-admin-input-credentials
          namespace: keycloak-system
---
apiVersion: role.keycloak.crossplane.io/v1alpha1
kind: Role
metadata:
  name: role
spec:
  providerConfigRef:
    name: keycloak-default
  forProvider:
    name: role
    realmId: acmecorp-00001
---
apiVersion: group.keycloak.crossplane.io/v1alpha1
kind: Group
metadata:
  name: group
spec:
  providerConfigRef:
    name: keycloak-default
  forProvider:
    name: group
    realmId: acmecorp-00001
---
apiVersion: group.keycloak.crossplane.io/v1alpha1
kind: Roles
metadata:
  name: group-roles
spec:
  providerConfigRef:
    name: keycloak-default
  forProvider:
    realmId: acmecorp-00001
    groupIdRef:
      name: group
    roleIdsRefs:
      - name: role
---
apiVersion: group.keycloak.crossplane.io/v1alpha1
kind: Memberships
metadata:
  name: membership
spec:
  providerConfigRef:
    name: keycloak-default
  forProvider:
    realmId: acmecorp-00001
    groupIdRef:
      name: group
    members:
      - user
```

This creates user with assigned group with single role. All good.
But if later somthing like this comes:

```
apiVersion: user.keycloak.crossplane.io/v1alpha1
kind: User
metadata:
  name: another-user
spec:
  providerConfigRef:
    name: keycloak-default
  forProvider:
    enabled: true
    realmId: acmecorp-00001
    username: another-user
    initialPassword:
      - temporary: false
        valueSecretRef:
          key: credentials
          name: initial-user-global-acmecorp-00001-admin-input-credentials
          namespace: keycloak-system
---
apiVersion: group.keycloak.crossplane.io/v1alpha1
kind: Memberships
metadata:
  name: another-membership
spec:
  providerConfigRef:
    name: keycloak-default
  forProvider:
    realmId: acmecorp-00001
    groupIdRef:
      name: group
    members:
      - another-user
```

The user **another-user** is given the group membership, however the user **user** loses it. The **another-membership** resource overwrites the existing list of group members.

**Comment by Breee** [comment]
does something like that work in terraform? 🤔

**Comment by vladimirblahoz** [comment]
Frankly, I have no clue (not a terraform specialist).
I was hoping that the functionality is very similar to assigning roles directly to users with **Roles.user.keycloak.crossplane.io** resource having the **exhaustive** flag. Now reading the docs again it claims that "manually" added roles aren't removed with it, so now I'm not really sure that even this does what I expected from it.

**Comment by Breee** [comment]
Hm, i'll check that out and tell you asap 😄

**Comment by vladimirblahoz** [comment]
I just checked that this (the situation with roles) works:

```
apiVersion: user.keycloak.crossplane.io/v1alpha1
kind: User
metadata:
  name: user
  labels:
    username: user
spec:
  providerConfigRef:
    name: keycloak-default
  forProvider:
    enabled: true
    realmId: acmecorp-00001
    username: user
    initialPassword:
      - temporary: false
        valueSecretRef:
          key: credentials
          name: initial-user-global-acmecorp-00001-admin-input-credentials
          namespace: keycloak-system
---
apiVersion: keycloak.ataccama.com/v1alpha1
kind: Role
metadata:
  name: mmm-role-1
  namespace: default
spec:
  identifier:
    tenant: acmecorp-00001
    label: role1
    component: mmm
---
apiVersion: keycloak.ataccama.com/v1alpha1
kind: Role
metadata:
  name: mmm-role-2
  namespace: default
spec:
  identifier:
    tenant: acmecorp-00001
    label: role2
    component: mmm
---
apiVersion: user.keycloak.crossplane.io/v1alpha1
kind: Roles
metadata:
  name: user-roles1
spec:
  providerConfigRef:
    name: keycloak-default
  forProvider:
    realmId: acmecorp-00001
    roleIdsRefs:
      - name: mmm-acmecorp-00001-role1
    exhaustive: false
    userIdRef:
      name: user
---
apiVersion: user.keycloak.crossplane.io/v1alpha1
kind: Roles
metadata:
  name: user-roles2
spec:
  providerConfigRef:
    name: keycloak-default
  forProvider:
    realmId: acmecorp-00001
    roleIdsRefs:
      - name: mmm-acmecorp-00001-role2
    exhaustive: false
    userIdRef:
      name: user
```

So apparently **Roles** resource is able to append the roles and you can have as many of them as you want targeting the same user as long as the **exhaustive** flag is set to **false**
