### ISSUE TITLE
Resource type: openid_user_realm_role_protocol_mapper

### ISSUE THREAD

**Issue by mircea-pavel-anton** [crossplane-contrib/provider-keycloak#160]
I am working on converting some Terraform manifests over to crossplane. I have a resource of this type:

https://registry.terraform.io/providers/mrparkers/keycloak/latest/docs/resources/openid_user_realm_role_protocol_mapper

I did not manage to find it while looking through the docs. Is it not supported?

**Comment by mircea-pavel-anton** [comment]
I managed to find an example in the documentation. Apparently it's a generic protocol mapper which we have to configure to cover different usecases:

```yaml
apiVersion: client.keycloak.crossplane.io/v1alpha1
kind: ProtocolMapper
metadata:
  name: openid-role-mapper
spec:
  forProvider:
    clientId: another-openid-client
    config:
      claim.name: roles
      multivalued: "true"
    name: role-mapper
    protocol: openid-connect
    protocolMapper: oidc-usermodel-realm-role-mapper
    realmId: another-realm
  providerConfigRef:
    name: keycloak-provider-config

```

link: https://marketplace.upbound.io/providers/crossplane-contrib/provider-keycloak/v1.4.0/resources/client.keycloak.crossplane.io/ProtocolMapper/v1alpha1
