### ISSUE TITLE
How to refer Subflow within Execution

### ISSUE THREAD

**Issue by tanalam2411** [crossplane-contrib/provider-keycloak#163]
In Execution spec there are options available to refer Parent Flow.

```yaml
apiVersion: authenticationflow.keycloak.crossplane.io/v1alpha1
kind: Execution
metadata:
  annotations:
    meta.upbound.io/example-id: authenticationflow/v1alpha1/execution
  labels:
    testing.upbound.io/example-name: execution_one
  name: execution-one
spec:
  forProvider:
    authenticator: auth-cookie
    parentFlowAliasSelector:
      matchLabels:
        testing.upbound.io/example-name: flow
    realmIdSelector:
      matchLabels:
        testing.upbound.io/example-name: realm
    requirement: ALTERNATIVE
```

Similar to this, how can we refer Parent SubFlow, as I want to add step within Subflow in KeyCloak authentication.

**Comment by Breee** [comment]
can  you make a full example of what you are trying to do / need?

**Comment by tanalam2411** [comment]
![image](https://github.com/user-attachments/assets/b8ff4fb1-31af-4f23-820e-e72a3f83fd7f)

I have configured this flow and added 2 steps using `Execution` MR and one `SubFlow` using `SubFlow` MR using this Provider.
But I want to add one step within `SubFlow` and for that I need to create MR of type `Execution` but it should resolve the reference to this `SubFlow` but I think it can only resolves for type `Flow`.

So, within `parentFlowAliasSelector` it should support resolvereference for both `Flow` and `SubFlow`.

```go
apiVersion: authenticationflow.keycloak.crossplane.io/v1alpha1
kind: Execution
metadata:
  name: execution-one
spec:
  forProvider:
    authenticator: auth-cookie
    parentFlowAliasSelector:
      matchLabels:
        testing.upbound.io/example-name: flow
    realmIdSelector:
      matchLabels:
        testing.upbound.io/example-name: realm
    requirement: ALTERNATIVE
    ```
    
    But if this is an inccorect assumption and there is some other way to add step within SubFlow then that would be helpful.

**Comment by jmisasa** [comment]
Can confirm `parentFlowAlias` works for both `Flow` and `SubFlow`. On the other hand, `parentFlowAliasRef` has only worked for us for `Flow` (I would think the same behavior would occur with `parentFlowAliasSelector`)

**Comment by Breee** [comment]
Its a similar issues as the one we have with OIDC and SAML client references. We are already working on this.  (https://github.com/crossplane-contrib/provider-keycloak/pull/311) 
The main pain point here is that crossplanes framework upjet does not support references for multiple types. 

That is why we most likely will need to add two fields: 

parentFlowAliasRef
parentSubFlowAliasRef

**Comment by Breee** [comment]
Will be available in `v2.12.0`

**Now this works ✅:**
```yaml
apiVersion: authenticationflow.keycloak.crossplane.io/v1alpha1
kind: Execution
metadata:
  name: execution-in-subflow
spec:
  forProvider:
    authenticator: auth-username-password-form
    # NEW: Can now reference Subflow resources
    parentSubflowAliasRef:
      name: my-subflow
    priority: 10
    realmIdRef:
      name: my-realm
    requirement: REQUIRED
  providerConfigRef:
    name: keycloak-provider-config
```

**Using selectors also works ✅:**
```yaml
apiVersion: authenticationflow.keycloak.crossplane.io/v1alpha1
kind: Execution
metadata:
  name: execution-with-selector
spec:
  forProvider:
    authenticator: auth-otp-form
    # NEW: Selector for Subflow resources
    parentSubflowAliasSelector:
      matchLabels:
        flow-type: authentication
    priority: 20
    realmIdRef:
      name: my-realm
    requirement: REQUIRED
  providerConfigRef:
    name: keycloak-provider-config
```
