### ISSUE TITLE
Adding a mapper to an existing client scope

### ISSUE THREAD

**Issue by greyarch** [crossplane-contrib/provider-keycloak#187]
Hey guys, great work so far!

I have the following problem:

I want to add a mapper to an existing client scope, namely the "profile" client scope.

This works fine if I use the clientScopeId, but this is not really a solution since the scope id is random uuid. 

Furthermore, I cannot match by label (using clientScopeIdSelector) since I am not creating the client scope, and there is no kuberentes/crossplane resource that corresponds to the scope.

I expected to be able to use clientScopeIdRef.name but this also seems to refer to the name of a kubernetes object and not the name of the client scope in keycloak.

I tried to create a ClientScope resource, that will not create the scope but will just reference it. This is, however, not possible - te provider tries to always create objects and if they already exist, it gives 409.

So... how should I do that?

Cheers!

**Comment by Breee** [comment]
Greetings,

You should be able to create the Ressource you want to reference in "Observe Only" Mode, for that lookup Management policies.

If you have more questions or Problems let me know

https://docs.crossplane.io/latest/guides/import-existing-resources/

**Comment by anushahg** [comment]
???

**Comment by greyarch** [comment]
Any development/news/comment here?

**Comment by Breee** [comment]
Sorry for the late reply, 
you are most likely missing the external name. 

```
metadata:
  annotations:
    crossplane.io/external-name: <UUID OR EXTERNAL_NAME>
``` 

should we add that to  https://gitlab.com/corewire/images/crossplane/function-keycloak-builtin-objects  
@b509  ?

**Comment by greyarch** [comment]
Hey @Breee, unfortunately adding this annotation does not work either.

I tried both:

```yaml
apiVersion: openidclient.keycloak.crossplane.io/v1alpha1
kind: ClientScope
metadata:
  name: my-scope
  annotations:
    crossplane.io/external-name: profile
spec:
  managementPolicies: ["Observe"]
  forProvider:
    realmId: "existing-realm"
    name: "profile"
  providerConfigRef:
    name: "dev" 
```

and (without the `forProvider.name`):

```yaml
apiVersion: openidclient.keycloak.crossplane.io/v1alpha1
kind: ClientScope
metadata:
  name: my-scope
  annotations:
    crossplane.io/external-name: profile
spec:
  managementPolicies: ["Observe"]
  forProvider:
    realmId: "existing-realm"
  providerConfigRef:
    name: "dev" 
```

Both result in `external resource does not exist`.

I vote "YES" on your question to @b509  :)
