### ISSUE TITLE
How to update one default `UserAttributeMapper` of a new `UserFederation`?

### ISSUE THREAD

**Issue by joneshf** [crossplane-contrib/provider-keycloak#201]
I'd like to create a new `UserFederation` and alter one of the default `UserAttributeMapper`s that gets created. I'm having a tough time figuring out how to do that without making every default mapper with the configuration I want. In particular, I'd like to change the default `UserAttributeMapper` for `firstName` to use `givenname` as the [`ldapAttribute`](https://marketplace.upbound.io/providers/crossplane-contrib/provider-keycloak/v1.9.2/resources/ldap.keycloak.crossplane.io/UserAttributeMapper/v1alpha1#doc:spec-forProvider-ldapAttribute) instead of the default `cn`.

For example, if I've got a setup like this:

```YAML
---
apiVersion: ldap.keycloak.crossplane.io/v1alpha1
kind: UserAttributeMapper
metadata:
  name: first-name
spec:
  forProvider:
    alwaysReadValueFromLdap: true
    isMandatoryInLdap: true
    # The `ldapAttribute` defaults to `cn`.
    # This `UserAttributeMapper` changes that to `givenname`.
    ldapAttribute: givenname
    ldapUserFederationIdRef:
      name: lldap
    name: first name
    readOnly: true
    realmIdRef:
      name: my-realm
    userModelAttribute: firstName
  providerConfigRef:
    name: my-provider

---
apiVersion: ldap.keycloak.crossplane.io/v1alpha1
kind: UserFederation
metadata:
  name: lldap
spec:
  forProvider:
    …
  providerConfigRef:
    name: my-provider
```

What ends up happening is that it creates an additional `UserAttributeMapper` with all the right configuration on the newly created `UserFederation`, instead of updating the `UserAttributeMapper` with the name `first name`. That makes sense, because these resources are effectively saying, "I want to add a new `UserAttributeMapper`." But that's not what I actually want.

One workaround is to use [`deleteDefaultMappers: true`](https://marketplace.upbound.io/providers/crossplane-contrib/provider-keycloak/v1.9.2/resources/ldap.keycloak.crossplane.io/UserFederation/v1alpha1#doc:spec-forProvider-deleteDefaultMappers) on the `UserFederation`, and create all of the (default) mappers with the configuration I want. I'm doing this in the short-term so I can have something working. But is there a different way to achieve the same goal of altering one field on a single mapper that doesn't involve recreating everything?
