### ISSUE TITLE
IdentityProviderMapper user_attribute not being mapped

### ISSUE THREAD

**Issue by DreamingRaven** [crossplane-contrib/provider-keycloak#257]
Hey I have an issue where I am trying to map azure entras preferred_username to an email attribute in keycloak. `claim` works as expected, but I cannot get the `user_attribute` set to email. Any information would be amazing, is my IdentityProviderMapper wrong, has anyone got a working example of this?

```
apiVersion: identityprovider.keycloak.crossplane.io/v1alpha1
kind: IdentityProviderMapper
metadata:
  name: azure-email-importer
spec:
  forProvider:
    realm: myrealm
    name: azure-email-importer
    identityProviderAlias: azure
    identityProviderMapper: oidc-user-attribute-idp-mapper
    extraConfig:
      claim: preferred_username
      user_attribute: email
```
## Output

![Image](https://github.com/user-attachments/assets/6bbf7621-8ff6-4036-af8d-0f809f25af66)

## Expected Output

![Image](https://github.com/user-attachments/assets/8c72badd-65c8-46c0-b136-ccaea9e75766)

# Appendix

example that doesnt seem to work I.E `Claim` instead of `claim` makes both extraConfig overrides disappear: https://github.com/crossplane-contrib/provider-keycloak/blob/f0f093fcd499ea93790fdf5bd9d00883905dbf5c/examples-generated/identityprovider/v1alpha1/identityprovidermapper.yaml#L1-L20

respective terraform module usage: https://registry.terraform.io/providers/keycloak/keycloak/latest/docs/resources/attribute_importer_identity_provider_mapper#example-usage

keycloak source property: https://github.com/keycloak/keycloak/blob/d089e23aef560f9d9ceb96490d68a64aa910b79b/services/src/main/java/org/keycloak/broker/oidc/mappers/UserAttributeMapper.java#L68-L72

identity provider mapper API: https://github.com/crossplane-contrib/provider-keycloak/blob/f0f093fcd499ea93790fdf5bd9d00883905dbf5c/apis/identityprovider/v1alpha1/zz_identityprovidermapper_types.go#L20

**Comment by Breee** [comment]
that resource implements: 

https://registry.terraform.io/providers/keycloak/keycloak/latest/docs/resources/custom_identity_provider_mapper#example-usage  

it states 

```
  # extra_config with syncMode is required in Keycloak 10+
  extra_config = {
    syncMode      = "INHERIT"
    Claim         = "my-email-claim"
    UserAttribute = "email"
  }
```


maybe you need the sync mode?  
i'll setup a test as well

**Comment by Breee** [comment]
so with something like that it kinda works: 

```
# This example demonstrates the minimum required fields to create a realm.
apiVersion: realm.keycloak.crossplane.io/v1alpha1
kind: Realm
metadata:
  name: dev  # The name of the realm in Kubernetes
spec:
  forProvider:
    realm: "dev"  # The name of the realm in Keycloak
  providerConfigRef:
    name: "keycloak-provider-config"  # Reference to the ProviderConfig resource
--- 
apiVersion: v1 
kind: Secret
metadata:
  name: example-secret
  namespace: default
type: Opaque
data:
  example-key: dGVzdA==
---
apiVersion: oidc.keycloak.crossplane.io/v1alpha1
kind: IdentityProvider
metadata:
  name: realm-identity-provider
spec:
  forProvider:
    alias: my-idp
    authorizationUrl: https://authorizationurl.com
    clientId: "test"
    clientSecretSecretRef:
      key: example-key
      name: example-secret
      namespace: default
    realm: dev
    tokenUrl: https://tokenurl.com
  providerConfigRef:
    name: "keycloak-provider-config"  # Reference to the ProviderConfig resource
--- 
apiVersion: identityprovider.keycloak.crossplane.io/v1alpha1
kind: IdentityProviderMapper
metadata:
  name: azure-email-importer
spec:
  forProvider:
    realm: dev
    name: azure-email-importer
    identityProviderAlias: my-idp 
    identityProviderMapper: "%s-user-attribute-idp-mapper"
    extraConfig:
      syncMode: "INHERIT"
      Claim: my-email-claim
      UserAttribute: email
      Category: 
  providerConfigRef:
    name: "keycloak-provider-config"  # Reference to the ProviderConfig resource
```

but i have some weird UI issues where the Category and Type is missing, i can also not open the mapper

**Comment by Breee** [comment]
Sadly those api docs do not help at all https://www.keycloak.org/docs-api/latest/rest-api/index.html#_identity_providers ^^
i'll check in the keycloak sourcecode

**Comment by DreamingRaven** [comment]
If it helps, I believe the property is here https://github.com/keycloak/keycloak/blob/d089e23aef560f9d9ceb96490d68a64aa910b79b/services/src/main/java/org/keycloak/broker/oidc/mappers/UserAttributeMapper.java#L68-L72

**Comment by DreamingRaven** [comment]
The interesting thing is this is different to the claim property, apparently its a `USER_PROFILE_ATTRIBUTE_LIST_TYPE`

**Comment by Breee** [comment]
Yes  https://github.com/keycloak/keycloak/blob/44956e10d00b79b0000583ed964130712abe5353/services/src/main/java/org/keycloak/broker/saml/mappers/XPathAttributeMapper.java#L60

```
--- 
apiVersion: identityprovider.keycloak.crossplane.io/v1alpha1
kind: IdentityProviderMapper
metadata:
  name: azure-email-importer
spec:
  forProvider:
    realm: dev
    name: azure-email-importer
    identityProviderAlias: my-idp 
    identityProviderMapper: "oidc-user-attribute-idp-mapper"
    extraConfig:
      syncMode: "INHERIT"
      claim: "my-email-claim"
      "user.attribute": email
  providerConfigRef:
    name: "keycloak-provider-config"  # Reference to the ProviderConfig resource
```
