### ISSUE TITLE
Group Role Mapper for Existing Client Role

### ISSUE THREAD

**Issue by DreamingRaven** [crossplane-contrib/provider-keycloak#262]
Hey,

I am trying to create a realm-admin group that has permission to administer the keycloak realm so I can assign this to given users.

I need to add this `realm-admin` role to my  group but the `realm-admin` role is pre-existing in keycloak associated to the `realm-management` client. However, I am unsure how I can add this client role to my admin group. This is what it should end up looking like:

![Image](https://github.com/user-attachments/assets/e2fe1c35-83f6-4ae4-b33a-3bf1173f7501)

How can I reference the client role in the `group.keycloak.crossplane.io/v1alpha1 Roles`?
 Here are two versions trying to accomplish this:

## Crossplane Provider Version

<details>

<summary>Crossplane Provider Version</summary>

```yaml
apiVersion: group.keycloak.crossplane.io/v1alpha1
kind: Group
metadata:
  name: realm-admin
spec:
  deletionPolicy: Delete
  forProvider:
    realmId: my-realm
    name: realm-admin
---
apiVersion: group.keycloak.crossplane.io/v1alpha1
kind: Roles
metadata:
  name: realm-admin
spec:
  forProvider:
    realmId: my-realm
    groupIdRef:
      name: realm-admin
    roleIdsRefs:
      # - name: "realm-management.realm-admin"
      # - name: "realm-management:realm-admin"
      - name: "realm-management/realm-admin" # <--- Uncertain how I can reference this pre-existing client role by name
  providerConfigRef:
    name: default
```

</details>

## Keycloak Terraform Provider Version

<details>
<summary>Keycloak Terraform Provider Version</summary>

```terraform
terraform {
  required_providers {
    keycloak = {
      source = "keycloak/keycloak"
      version = ">= 5.1.1"
    }
  }
}

provider "keycloak" {
    url = "http://localhost:8078"
    base_path = "/"
    client_id = "admin-cli"
    username = "admin"
    password = "password"
}

resource "keycloak_realm" "realm" {
  realm   = "my-realm"
  enabled = true
}

resource "keycloak_group" "realm_admin_group" {
  realm_id = keycloak_realm.realm.id
  name     = "realm_admin"
}

resource "keycloak_group_roles" "realm_admin_group_roles" {
  realm_id = keycloak_realm.realm.id
  group_id = keycloak_group.realm_admin_group.id

  role_ids = [
    "realm-management/realm-admin" # <--- I realise this should be an ID but since its pre-existing im uncertain how I can reference it without having to import the resource into terraform for instance.
  ]
}

```
an env file for docker compose:
```yaml
POSTGRES_DB=keycloak_db
POSTGRES_USER=keycloak_db_user
POSTGRES_PASSWORD=keycloak_db_user_password
KEYCLOAK_ADMIN=admin
KEYCLOAK_ADMIN_PASSWORD=password
```
and an associated docker-compose for local testing:
```yaml
version: '3.7'

services:
  postgres:
    image: postgres:17.2
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    networks:
      - keycloak_network

  keycloak:
    image: quay.io/keycloak/keycloak:26.0.7
    command: start
    environment:
      KC_HOSTNAME: localhost
      KC_HOSTNAME_PORT: "8080"
      KC_HOSTNAME_STRICT_BACKCHANNEL: "false"
      KC_HTTP_ENABLED: "true"
      KC_HOSTNAME_STRICT_HTTPS: "false"
      KC_HEALTH_ENABLED: "true"
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres/${POSTGRES_DB}
      KC_DB_USERNAME: ${POSTGRES_USER}
      KC_DB_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - 127.0.0.1:8078:8080
    restart: always
    depends_on:
      - postgres
    networks:
      - keycloak_network

volumes:
  postgres_data:
    driver: local

networks:
  keycloak_network:
    driver: bridge
```
</details>

Thanks, and sorry for taking your time!

Terraform keycloak provider group_roles resource https://registry.terraform.io/providers/keycloak/keycloak/latest/docs/resources/group_roles

EDIT: related discussions:

- https://github.com/crossplane-contrib/provider-keycloak/issues/144
- https://github.com/crossplane-contrib/provider-keycloak/pull/206
