### ISSUE TITLE
Issue when creating role mapping for client and realm role

### ISSUE THREAD

**Issue by a936455** [crossplane-contrib/provider-keycloak#275]
Hi Team,

I am trying to create role mapping for existing client id and realm role
Below is my composition:

apiVersion: client.keycloak.crossplane.io/v1alpha1
kind: RoleMapper
metadata:
  name: test-rol-assigment
  namespace: vcontrolplane
spec:
  providerConfigRef:
    name: "keyclock-provider-config"
  deletionPolicy: Delete
  forProvider:
    clientId: test-sn-client-id
    realmId: master
    roleId: gateway-route-api-reader

while running I get below error

Warning  CannotCreateExternalResource  6s                   managed/client.keycloak.crossplane.io/v1alpha1, kind=rolemapper  async create failed: failed to create the resource: [{0 error sending GET request to /admin/realms/master/roles-by-id/gateway-route-api-reader: 404 Not Found. Response body: {"error":"Could not find role with id"}  []}]

Can someone please tell me what is wrong here ?

**Comment by Breee** [comment]
Greetings, 

- `roleId: gateway-route-api-reader` is wrong there. Keycloak references things by a weird UUID sadly. 

here is two examples on how to do this

## Example 1:  

In the current release we still need to reference by UUIDs when importing resources.

```yaml
---
apiVersion: openidclient.keycloak.crossplane.io/v1alpha1
kind: Client
metadata:
  name: my-imported-client
  annotations:
    crossplane.io/external-name: 86ebad57-08f8-40b7-9b3e-8633dd5a9b92
  namespace: dev
spec:
  managementPolicies:
  - Observe
  deletionPolicy: Orphan
  forProvider:
    realmId: "master"
    accessType: "CONFIDENTIAL"
    clientId: "my-client"
    serviceAccountsEnabled: true
  providerConfigRef:
    name: "keycloak-provider-config"
---
apiVersion: role.keycloak.crossplane.io/v1alpha1
kind: Role
metadata:
  annotations:
    crossplane.io/external-name: f53f2af8-42af-4a36-bb79-a70b3bc39c29
  name: my-imported-role
  namespace: dev
spec:
  deletionPolicy: Orphan
  forProvider:
    name: my-role
    realmId: master
  managementPolicies:
  - Observe
  providerConfigRef:
    name: "keycloak-provider-config"
--- 
apiVersion: client.keycloak.crossplane.io/v1alpha1
kind: RoleMapper
metadata:
  name: my-rolemapper
  namespace: dev
spec:
  providerConfigRef:
    name: "keycloak-provider-config"
  deletionPolicy: Delete
  forProvider:
    clientIdRef:
      name: my-imported-client
    realmId: master
    roleIdRef: 
      name: my-imported-role
```

## Example 2
-  `xpkg.upbound.io/crossplane-contrib/provider-keycloak:v2.0.0-rc.1` is the pre-release of an upcoming version, which allows you to reference by  `<realm>/<rolename>` 

```yaml
---
apiVersion: openidclient.keycloak.crossplane.io/v1alpha1
kind: Client
metadata:
  name: my-imported-client
  annotations:
    crossplane.io/external-name: master/my-client
  namespace: dev
spec:
  managementPolicies:
  - Observe
  deletionPolicy: Orphan
  forProvider:
    realmId: "master"
    accessType: "CONFIDENTIAL"
    clientId: "my-client"
    serviceAccountsEnabled: true
  providerConfigRef:
    name: "keycloak-provider-config"
---
apiVersion: role.keycloak.crossplane.io/v1alpha1
kind: Role
metadata:
  annotations:
    crossplane.io/external-name: master/my-role
  name: my-imported-role
  namespace: dev
spec:
  deletionPolicy: Orphan
  forProvider:
    name: my-role
    realmId: master
  managementPolicies:
  - Observe
  providerConfigRef:
    name: "keycloak-provider-config"
--- 
apiVersion: client.keycloak.crossplane.io/v1alpha1
kind: RoleMapper
metadata:
  name: my-rolemapper
  namespace: dev
spec:
  providerConfigRef:
    name: "keycloak-provider-config"
  deletionPolicy: Delete
  forProvider:
    clientIdRef:
      name: my-imported-client
    realmId: master
    roleIdRef: 
      name: my-imported-role
```
