### ISSUE TITLE
Invalid provider type or no such provider when creating GroupMapper

### ISSUE THREAD

**Issue by theodor-franke** [crossplane-contrib/provider-keycloak#299]
iam trying to create a `GroupMapper` for a `UserFederation`. 

```yaml
apiVersion: ldap.keycloak.crossplane.io/v1alpha1
kind: GroupMapper
metadata:
  name: ldap-group-mapper
  namespace: keycloak
spec:
  providerConfigRef:
    name: "keycloak-provider-config"
  forProvider:
    name: "ldap-group-mapper"
    realmIdRef:
      name: "my-realm"
    ldapUserFederationIdRef:
      name: "ldap-federation"
    ldapGroupsDn: "ou=Groups, dc=intra, dc=company, dc=eu"
    mode: "READ_ONLY"
    groupNameLdapAttribute: "cn"
    groupObjectClasses:
      - "group"
    preserveGroupInheritance: true
    membershipAttributeType: "dn"
    membershipLdapAttribute: "member"
    membershipUserLdapAttribute: "cn"
    memberofLdapAttribute: "memberOf"
    groupsPath: "/ad/"
```

But the CRD get the Status: `CannotCreateExternalResource` with the message:

```
async create failed: failed to create the resource: [{0 error sending POST request to /admin/realms/mycompany/components: 400 Bad Request. Response body: {"error":"Invalid provider type or no such provider"}  ]}]
```

is there something wrong with my config?

**Comment by Breee** [comment]
Greetings, sorry i was on vacation. 

Can you please send me all of your ressources? 
I see : 

```
    realmIdRef:
      name: "my-realm"
    ldapUserFederationIdRef:
      name: "ldap-federation"
```

these refer to Kubernetes objects

**Comment by theodor-franke** [comment]
```yaml
apiVersion: realm.keycloak.crossplane.io/v1alpha1
kind: Realm
metadata:
  name: my-realm
  namespace: keycloak
spec:
  forProvider:
    realm: myrealm
    displayName: "MY-Realm"
  providerConfigRef:
    name: keycloak-provider-config
```

```yaml
apiVersion: ldap.keycloak.crossplane.io/v1alpha1
kind: UserFederation
metadata:
  name: ldap-federation
  namespace: keycloak
spec:
  providerConfigRef:
    name: keycloak-provider-config
  forProvider:
    name: ldap-federation
    realmIdRef:
      name: my-realm
   ...
    bindCredentialSecretRef:
      name: ldap-keycloak-password
      namespace: keycloak
      key: password
```
