### ISSUE TITLE
Error using matchLabels and matchControllerRef in Compositions

### ISSUE THREAD

**Issue by elizabeth-bean** [crossplane-contrib/provider-keycloak#300]
For reference, we are on provider-keycloak 2.0.0, Crossplane 1.19.1, and Keycloak 26.0.2

My project uses an XRD and Composition to define XRs, which in turn create nested groups. These groups use matchLabels and matchControllerRef in the GroupIdSelector to nest the child groups under the root group, as seen below.

```
apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xteamtests.team.department.company.domain
spec:
  defaultCompositeDeletePolicy: Foreground
  group: team.department.company.domain
  names:
    kind: XTeamTest
    plural: xteamtests
  versions:
    - name: v1alpha1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                parameters:
                  type: object
                  properties:
                    name:
                      type: string
                    groupName: 
                      type: string
                  required:
                    - name
                    - groupName
              required:
                - parameters
            status:
              type: object
              properties:
                policyId:
                  type: string

apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: xteamtests.team.department.company.domain
  labels:
    broker: keycloaktest
spec:
  writeConnectionSecretsToNamespace: crossplane-system
  compositeTypeRef:
    apiVersion: team.department.company.domain/v1alpha1
    kind: XTeamTest
  mode: Pipeline
  pipeline:
    - step: environmentConfigs
      functionRef:
        name: function-environment-configs
      input:
        apiVersion: environmentconfigs.fn.crossplane.io/v1beta1
        kind: Input
        spec:
          environmentConfigs:
            - type: Reference
              ref:
                name: keycloak
    - step: pt0
      functionRef:
        name: function-patch-and-transform
      input:
        apiVersion: pt.fn.crossplane.io/v1beta1
        kind: Resources
        patchSets:
          - name: groups
            patches:
              - fromFieldPath: spec.parameters.name
                toFieldPath: metadata.labels[department.company.domain/team]
              - type: FromEnvironmentFieldPath
                fromFieldPath: realm-id
                toFieldPath: spec.forProvider.realmId
          - name: children
            patches:
              - fromFieldPath: spec.parameters.name
                toFieldPath: spec.forProvider.parentIdSelector.matchLabels[department.company.domain/team]
    
          - name: policy
            patches:
              - type: FromEnvironmentFieldPath
                fromFieldPath: realm-id
                toFieldPath: spec.forProvider.realmId
              - fromFieldPath: spec.parameters.name
                toFieldPath: spec.forProvider.groupIdSelector.matchLabels[department.company.domain/team]
              - fromFieldPath: "status.policyId"
                toFieldPath: "spec.forProvider.manageMembershipScope[0].policies[0]"
                policy:
                  fromFieldPath: Required
              - fromFieldPath: "status.policyId"
                toFieldPath: "spec.forProvider.viewMembersScope[0].policies[0]"
                policy:
                  fromFieldPath: Required
              - fromFieldPath: "status.policyId"
                toFieldPath: "spec.forProvider.viewScope[0].policies[0]"
                policy:
                  fromFieldPath: Required
        resources:
          - name: group-root
            base:
              apiVersion: group.keycloak.crossplane.io/v1alpha1
              kind: Group
              metadata:
                labels:
                  department.company.domain/role: roottest
            patches:
              - type: PatchSet
                patchSetName: groups

              - fromFieldPath: spec.parameters.groupName
                toFieldPath: spec.forProvider.name

          - name: group-admin
            base:
              apiVersion: group.keycloak.crossplane.io/v1alpha1
              kind: Group
              metadata:
                labels:
                  department.company.domain/role: administrator
              spec:
                forProvider:
                  name: administrator
                  parentIdSelector:
                    matchLabels:
                      department.company.domain/role: roottest
                    matchControllerRef: true
                    policy:
                      resolution: Required
            patches:
              - type: PatchSet
                patchSetName: groups

              - type: PatchSet
                patchSetName: children

              - type: ToEnvironmentFieldPath
                fromFieldPath: status.atProvider.id
                toFieldPath: admin-group-id
                policy:
                  fromFieldPath: Required
```

In upgrading from v1.13.0 to v2.0.0, matchControllerRef and matching multiple labels with matchLabels seems to have broken. Where we had seen the expected behavior with previous versions, with v2.0.0 we are seeing the child groups try to nest under the wrong parent more often than not. This produces the below outputs when creating a second XR from a composition:

```
NAME                        SYNCED   READY   EXTERNAL-NAME                          AGE
team-test-1-mgffb           True     True    3363f019-bcef-4971-8d17-b98315acd4ed   73s
team-test-1-tnx62           True     True    29164199-1026-4579-8802-ad16d37b3340   73s
team-test-2-k8bbw           True     True    8a35be01-210c-4cd0-8f71-05622bde30c1   13s
team-test-2-rdv4h           False    True    29164199-1026-4579-8802-ad16d37b3340   13s

Name:         team-test-2-rdv4h
Namespace:    
Labels:       crossplane.io/claim-name=
              crossplane.io/claim-namespace=
              crossplane.io/composite=team-test-2
              department.company.domain/role=administrator
              department.company.domain/team=team-test-2
Annotations:  crossplane.io/composition-resource-name: group-admin
              crossplane.io/external-name: 29164199-1026-4579-8802-ad16d37b3340
API Version:  group.keycloak.crossplane.io/v1alpha1
Kind:         Group
Metadata:
  Creation Timestamp:  2025-05-09T17:40:37Z
  Finalizers:
    finalizer.managedresource.crossplane.io
  Generate Name:  team-test-2-
  Generation:     3
  Owner References:
    API Version:           team.department.company.domain/v1alpha1
    Block Owner Deletion:  true
    Controller:            true
    Kind:                  XTeamTest
    Name:                  team-test-2
    UID:                   511e5577-454d-4a52-88fa-3093e79b6141
  Resource Version:        1341190205
  UID:                     fec81642-fee8-4a82-973d-9398d181f94e
Spec:
  Deletion Policy:  Delete
  For Provider:
    Name:       administrator
    Parent Id:  8a35be01-210c-4cd0-8f71-05622bde30c1
    Parent Id Ref:
      Name:  team-test-2-k8bbw
    Parent Id Selector:
      Match Controller Ref:  true
      Match Labels:
        department.company.domain/role:  roottest
        department.company.domain/team:  team-test-2
      Policy:
        Resolution:  Required
    Realm Id:        test-realm
  Init Provider:
  Management Policies:
    *
  Provider Config Ref:
    Name:  default
Status:
  At Provider:
    Id:         29164199-1026-4579-8802-ad16d37b3340
    Name:       administrator
    Parent Id:  3363f019-bcef-4971-8d17-b98315acd4ed
    Path:       /team-test-1/administrator
    Realm Id:   test-realm
  Conditions:
    Last Transition Time:  2025-05-09T17:40:42Z
    Message:               update failed: async update failed: refuse to update the external resource because the following update requires replacing it: cannot change the value of the argument "parent_id" from "3363f019-bcef-4971-8d17-b98315acd4ed" to "8a35be01-210c-4cd0-8f71-05622bde30c1"
    Reason:                ReconcileError
    Status:                False
    Type:                  Synced
    Last Transition Time:  2025-05-09T17:40:42Z
    Message:               async update failed: refuse to update the external resource because the following update requires replacing it: cannot change the value of the argument "parent_id" from "3363f019-bcef-4971-8d17-b98315acd4ed" to "8a35be01-210c-4cd0-8f71-05622bde30c1"
    Reason:                AsyncUpdateFailure
    Status:                False
    Type:                  LastAsyncOperation
    Last Transition Time:  2025-05-09T17:40:42Z
    Reason:                Available
    Status:                True
    Type:                  Ready
Events:
  Type     Reason                           Age                  From                                                       Message
  ----     ------                           ----                 ----                                                       -------
  Warning  CannotResolveResourceReferences  113s                 managed/group.keycloak.crossplane.io/v1alpha1, kind=group  cannot resolve references: mg.Spec.ForProvider.ParentID: referenced field was empty (referenced resource may not yet be ready)
  Normal   UpdatedExternalResource          110s                 managed/group.keycloak.crossplane.io/v1alpha1, kind=group  Successfully requested update of external resource
  Warning  CannotUpdateExternalResource     59s (x23 over 110s)  managed/group.keycloak.crossplane.io/v1alpha1, kind=group  async update failed: refuse to update the external resource because the following update requires replacing it: cannot change the value of the argument "parent_id" from "3363f019-bcef-4971-8d17-b98315acd4ed" to "8a35be01-210c-4cd0-8f71-05622bde30c1"
```

Although the spec itself seems to have the correct parent, the status.atProvider shows the wrong parent for the second XR and does not create the corresponding resource in Keycloak.

**Comment by Breee** [comment]
@denniskniep any idea why this is related to v2.0.0 ?

**Comment by elizabeth-bean** [comment]
Hello, I was wondering if anyone has had a chance to reproduce this issue or have any workarounds. I have observed the issue outside of an XRD as well now, with Group resources when trying to match labels or a parentIdRef to create a child group. Thanks!

**Comment by Breee** [comment]
For me parents and childs work on version `v2.1.0` : 

```
---
apiVersion: group.keycloak.crossplane.io/v1alpha1
kind: Group
metadata:
  name: test-parent
spec:
  deletionPolicy: Delete
  forProvider:
    name: test-parent
    realmId: dev
  providerConfigRef:
    name: "keycloak-provider-config"
---
apiVersion: group.keycloak.crossplane.io/v1alpha1
kind: Group
metadata:
  name: test-child
spec:
  deletionPolicy: Delete
  forProvider:
    name: test-child
    realmId: dev
    parentIdRef:
      name: test-parent
  providerConfigRef:
    name: "keycloak-provider-config"
```

can you please provide an example thats broken?

**Comment by elizabeth-bean** [comment]
Here are a couple test resources you can try. We are using matchLabels with multiple labels to apply child groups to the correct parent. The first set applies fine, but test-child-2 tries to apply to the wrong parent:

```
apiVersion: group.keycloak.crossplane.io/v1alpha1
kind: Group
metadata:
  name: test-parent-1
  labels:
    role: parent
    parent: test1
spec:
  deletionPolicy: Delete
  forProvider:
    name: test-parent-1
    realmId: dev
---
apiVersion: group.keycloak.crossplane.io/v1alpha1
kind: Group
metadata:
  name: test-child
  labels:
    role: child
spec:
  deletionPolicy: Delete
  forProvider:
    name: test-child
    realmId: dev
    parentIdSelector:
      matchLabels: 
        role: parent
        parent: test1
---
apiVersion: group.keycloak.crossplane.io/v1alpha1
kind: Group
metadata:
  name: test-parent-2
  labels:
    role: parent
    parent: test2
spec:
  deletionPolicy: Delete
  forProvider:
    name: test-parent-2
    realmId: dev
---
apiVersion: group.keycloak.crossplane.io/v1alpha1
kind: Group
metadata:
  name: test-child-2
  labels:
    role: child
spec:
  deletionPolicy: Delete
  forProvider:
    name: test-child
    realmId: dev
    parentIdSelector:
      matchLabels: 
        role: parent
        parent: test2
```
