### ISSUE TITLE
With user roles is there a way to match users created outside the provider?

### ISSUE THREAD

**Issue by tmyroadctfig** [crossplane-contrib/provider-keycloak#304]
I've created a crossplane managed `Role`, and user `Roles`, and I'm wondering whether I can match users created outside of the provider. E.g. with:

```
apiVersion: user.keycloak.crossplane.io/v1alpha1
kind: Roles
metadata:
  name: admin-roles
spec:
  forProvider:
    realmId: my-realm
    exhaustive: false
    roleIdsRefs:
      - name: my-crossplane-admin-role1
    userIdSelector:
        ???
  providerConfigRef:
    name: keycloak
```

Is there an alternative to `userIdSelector` which could match a name or attribute on the keycloak user? It seems like `matchLabels` only works against crossplane managed user resources?
