### ISSUE TITLE
Unable to create a GroupMembershipProtocolMapper that targets a ClientScope

### ISSUE THREAD

**Issue by aslafy-z** [crossplane-contrib/provider-keycloak#305]
I'm trying to create a GroupMembershipProtocolMapper that targets a ClientScope instead of a Client. 
As you can see https://registry.terraform.io/providers/keycloak/keycloak/latest/docs/resources/openid_group_membership_protocol_mapper#example-usage-client-scope and https://github.com/keycloak/terraform-provider-keycloak/blob/main/provider/resource_keycloak_openid_group_membership_protocol_mapper.go#L99-L103, this is a supported use case.

Here's my resource:
 
```yaml
apiVersion: openidgroup.keycloak.crossplane.io/v1alpha1
kind: GroupMembershipProtocolMapper
metadata:
  name: groups-mapper
spec:
  deletionPolicy: Delete
  forProvider:
    claimName: groups
    clientScopeIdRef:
      name: groups-scope
    fullPath: false
    name: groups
    realmIdRef:
      name: myrealm
  managementPolicies:
    - '*'
  providerConfigRef:
    name: keycloak-provider-config
```

- Realm exists and gets mapped to `spec.forProvider.realmId: myrealm`
- Client Scope exists and gets mapped to  `spec.forProvider.clientScopeId: 8dd40d66-b6ae-4223-881c-71958a99b597`

However, the resource fails to sync:

```yaml
# 2025-05-22T10:37:17Z    DEBUG    provider-keycloak    Cannot connect to provider    
controller: managed/openidgroup.keycloak.crossplane.io/v1alpha1, kind=groupmembershipprotocolmapper
request:
  name: groups-mapper
uid: ae592e91-330f-4c53-b43b-3778fccad0af
version: "36452"
external-name: ""
error: 'cannot initialize the Terraform plugin SDK async external client: failed to get the extended parameters for resource "groups-mapper": cannot get ID: required param client_id not set'
errorVerbose: |
  required param 'client_id' not set
  cannot get ID
  github.com/crossplane/upjet/pkg/controller.getExtendedParameters
    github.com/crossplane/upjet@v1.4.2/pkg/controller/external_tfpluginsdk.go: 146
  github.com/crossplane/upjet/pkg/controller.(*TerraformPluginSDKConnector).Connect
    github.com/crossplane/upjet@v1.4.2/pkg/controller/external_tfpluginsdk.go: 241
  github.com/crossplane/upjet/pkg/controller.(*TerraformPluginSDKAsyncConnector).Connect
    github.com/crossplane/upjet@v1.4.2/pkg/controller/external_async_tfpluginsdk.go: 55
  github.com/crossplane/crossplane-runtime/pkg/reconciler/managed.(*NopDisconnecter).Connect
    github.com/crossplane/crossplane-runtime@v1.16.0/pkg/reconciler/managed/reconciler.go: 246
  github.com/crossplane/crossplane-runtime/pkg/reconciler/managed.(*Reconciler).Reconcile
    github.com/crossplane/crossplane-runtime@v1.16.0/pkg/reconciler/managed/reconciler.go: 892
  github.com/crossplane/crossplane-runtime/pkg/ratelimiter.(*Reconciler).Reconcile
    github.com/crossplane/crossplane-runtime@v1.16.0/pkg/ratelimiter/reconciler.go: 54
  sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile
    sigs.k8s.io/controller-runtime@v0.17.3/pkg/internal/controller/controller.go: 119
  sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler
    sigs.k8s.io/controller-runtime@v0.17.3/pkg/internal/controller/controller.go: 316
  sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
    sigs.k8s.io/controller-runtime@v0.17.3/pkg/internal/controller/controller.go: 266
  sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2
    sigs.k8s.io/controller-runtime@v0.17.3/pkg/internal/controller/controller.go: 227
  runtime.goexit
    runtime/asm_amd64.s: 1700
  failed to get the extended parameters for resource \"k8saas-group-test\"
  github.com/crossplane/upjet/pkg/controller.(*TerraformPluginSDKConnector).Connect
    github.com/crossplane/upjet@v1.4.2/pkg/controller/external_tfpluginsdk.go: 243
  github.com/crossplane/upjet/pkg/controller.(*TerraformPluginSDKAsyncConnector).Connect
    github.com/crossplane/upjet@v1.4.2/pkg/controller/external_async_tfpluginsdk.go: 55
  github.com/crossplane/crossplane-runtime/pkg/reconciler/managed.(*NopDisconnecter).Connect
    github.com/crossplane/crossplane-runtime@v1.16.0/pkg/reconciler/managed/reconciler.go: 246
  github.com/crossplane/crossplane-runtime/pkg/reconciler/managed.(*Reconciler).Reconcile
    github.com/crossplane/crossplane-runtime@v1.16.0/pkg/reconciler/managed/reconciler.go: 892
  github.com/crossplane/crossplane-runtime/pkg/ratelimiter.(*Reconciler).Reconcile
    github.com/crossplane/crossplane-runtime@v1.16.0/pkg/ratelimiter/reconciler.go: 54
  sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile
    sigs.k8s.io/controller-runtime@v0.17.3/pkg/internal/controller/controller.go: 119
  sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler
    sigs.k8s.io/controller-runtime@v0.17.3/pkg/internal/controller/controller.go: 316
  sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
    sigs.k8s.io/controller-runtime@v0.17.3/pkg/internal/controller/controller.go: 266
  sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2
    sigs.k8s.io/controller-runtime@v0.17.3/pkg/internal/controller/controller.go: 227
  runtime.goexit
    runtime/asm_amd64.s: 1700
  cannot initialize the Terraform plugin SDK async external client
  github.com/crossplane/upjet/pkg/controller.(*TerraformPluginSDKAsyncConnector).Connect
    github.com/crossplane/upjet@v1.4.2/pkg/controller/external_async_tfpluginsdk.go: 57
  github.com/crossplane/crossplane-runtime/pkg/reconciler/managed.(*NopDisconnecter).Connect
    github.com/crossplane/crossplane-runtime@v1.16.0/pkg/reconciler/managed/reconciler.go: 246
  github.com/crossplane/crossplane-runtime/pkg/reconciler/managed.(*Reconciler).Reconcile
    github.com/crossplane/crossplane-runtime@v1.16.0/pkg/reconciler/managed/reconciler.go: 892
  github.com/crossplane/crossplane-runtime/pkg/ratelimiter.(*Reconciler).Reconcile
    github.com/crossplane/crossplane-runtime@v1.16.0/pkg/ratelimiter/reconciler.go: 54
  sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile
    sigs.k8s.io/controller-runtime@v0.17.3/pkg/internal/controller/controller.go: 119
  sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler
    sigs.k8s.io/controller-runtime@v0.17.3/pkg/internal/controller/controller.go: 316
  sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
    sigs.k8s.io/controller-runtime@v0.17.3/pkg/internal/controller/controller.go: 266
  sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2
    sigs.k8s.io/controller-runtime@v0.17.3/pkg/internal/controller/controller.go: 227
  runtime.goexit
    runtime/asm_amd64.s: 1700
```

I'm new to crossplane and have no idea how to fix this. However, I found that there may be a missing `client_scope_id` entry here: https://github.com/crossplane-contrib/provider-keycloak/blob/main/config/provider.go#L120. 

Let me know if I can provide any additional details!

**Comment by Breee** [comment]
that is already implemented, i guess you are missing  the error: 

```
 [cannot get ID: required param client_id not set](error: 'cannot initialize the Terraform plugin SDK async external client: failed to get the extended parameters for resource "groups-mapper": cannot get ID: required param client_id not set')
``` 

you have not set a `client_id` : 

```
apiVersion: openidgroup.keycloak.crossplane.io/v1alpha1
kind: GroupMembershipProtocolMapper
metadata:
  name: groups-mapper
spec:
  deletionPolicy: Delete
  forProvider:
    claimName: groups
    clientIdRef: 
       name: <YOUR CLIENT>
    clientScopeIdRef:
      name: groups-scope
    fullPath: false
    name: groups
    realmIdRef:
      name: myrealm
  managementPolicies:
    - '*'
  providerConfigRef:
    name: keycloak-provider-config
```
