### ISSUE TITLE
Mapping roles to group

### ISSUE THREAD

**Issue by ZipZipa** [crossplane-contrib/provider-keycloak#330]
I can't solve my problem. I need to dynamically assign roles to groups. I created such a manifest:

```
---
apiVersion: group.keycloak.upbound.io/v1alpha1
kind: Roles
metadata:
  name: foo
spec:
  forProvider:
    realmId: develop
    groupIdRef:
      name: "group-name"
    roleIdsRefs:
      - name: "roles-name"
```

When I have a second role, I have to manually update `roleIdsRefs`, but I want to automate this. How I can do this?

**Comment by Breee** [comment]
Greetings, sorry for the late reply. 

You could work with label selectors:  https://marketplace.upbound.io/providers/crossplane-contrib/provider-keycloak/v2.1.0/resources/group.keycloak.crossplane.io/Roles/v1alpha1#doc:spec-forProvider-roleIdsSelector 

```
---
apiVersion: group.keycloak.upbound.io/v1alpha1
kind: Roles
metadata:
  name:  adminroles
spec:
  forProvider:
    realmId: develop
    groupIdRef:
      name: "admins"
    roleIdsSelector:
      matchLabels: 
         roletype: adminrole
     policy:
       resolve: "Alyways"
```
