### ISSUE TITLE
feature: Allow ability to pass in root ca in the provider config

### ISSUE THREAD

**Issue by A1994SC** [crossplane-contrib/provider-keycloak#6]
## Issue

There does not seem to be a way to pass the `root_ca_certificate` argument to the terraform provider, link [here](https://registry.terraform.io/providers/mrparkers/keycloak/latest/docs#root_ca_certificate)

## Current solution

```yaml
apiVersion: pkg.crossplane.io/v1beta1
kind: DeploymentRuntimeConfig
metadata:
  name: intra-ca-trust
spec:
  deploymentTemplate:
    spec:
      replicas: 1
      selector: {}
      template:
        spec:
          initContainers:
          - name: update-trust
            image: docker.io/library/alpine:3.18.4
            resources:
              limits:
                cpu: 100m
                memory: 256Mi
              requests:
                cpu: 10m
                memory: 32Mi
            securityContext:
              runAsNonRoot: true
              runAsUser: 65532
              runAsGroup: 65532
              allowPrivilegeEscalation: false
              privileged: false
            volumeMounts:
            - mountPath: /certs
              name: ca-certs
            - mountPath: /tmp/ssl
              name: trust-store
            command:
            - sh
            - '-c'
            - |
              cp -r /etc/ssl/. /tmp/ssl/
              cat /certs/intra.ca-bundle >> /etc/adrp/ssl/certs/ca-certificates.crt
              echo "Updated /etc/ssl/certs/ca-certificates.crt"
          containers:
          - name: package-runtime
            volumeMounts:
            - mountPath: /certs
              name: ca-certs
            - mountPath: /etc/ssl
              name: trust-store
          volumes:
          - name: trust-store
            emptyDir:
              sizeLimit: 512Mi
```

## Changes

Add the ability to specify the `root_ca_certificate` like in the example `credentials` below that will get passed to the terraform provider.

```json
{
  "client_id": "admin-cli",
  "username": "admin",
  "password": "sercurePassword",
  "url": "https://keycloak.example.com",
  "base_path": "/auth",
  "realm": "master",
  "root_ca_certificate": "/certs/intra.ca-bundle"
}
```
