### ISSUE TITLE
Provider keeps adding `UPDATE_PASSWORD` to user required actions

### ISSUE THREAD

**Issue by a1994sc** [crossplane-contrib/provider-keycloak#62]
I am using keycloak version `21.1.1` with the provider `v0.10.0` and after changing my initial password and waiting a few minutes the action `UPDATE_PASSWORD` is added to the required actions...

```yaml
apiVersion: user.keycloak.crossplane.io/v1alpha1
kind: User
metadata:
  name: aconlon
spec:
  deletionPolicy: Delete
  providerConfigRef:
    name: keycloak
  forProvider:
    realmIdRef:
      name: company
    username: aconlon
    email: allen@conlon.dev
    emailVerified: true
    firstName: Allen
    lastName: Conlon
    requiredActions: []
    initialPassword:
    - temporary: true
      valueSecretRef:
        key: password
        name: keycloak-initial-password
        namespace: crossplane-system
```

```yaml
# kubectl get user.user aconlon -o yaml

apiVersion: user.keycloak.crossplane.io/v1alpha1
kind: User
...
spec:
  forProvider:
    requiredActions:
    - UPDATE_PASSWORD
```

I tried to see if this was an issue with the upstream terraform provider, but I did not see anything in the issues.... 

Any help would be awesome, thanks.
