### ISSUE TITLE
Example of how to use ClientServiceAccountRole

### ISSUE THREAD

**Issue by olav-st** [crossplane-contrib/provider-keycloak#71]
Hi. First of all, thanks for this project! :smiley: 

It would be nice to have an example of how to use the `ClientServiceAccountRole`. I'm trying to use it to assign a role from the built-in `realm-management` client, but I haven't found a way to do that so far.

I have tried the examples in the `examples-generated/` folder, but they fail with the following error message:
```yaml
status:
  atProvider: {}
  conditions:
  - lastTransitionTime: "2024-03-02T13:07:02Z"
    message: 'observe failed: cannot run refresh: refresh failed: Reference to undeclared
      resource: A managed resource "keycloak_openid_client" "client2" has not been
      declared in the root module.'
    reason: ReconcileError
    status: "False"
    type: Synced
```
Even though `client2` exists:
```bash
$ kubectl get client
NAME              READY   SYNCED   EXTERNAL-NAME                                  AGE
client1           True    True     fbe5e90f-7968-4ed4-9b9f-e9d7930fc164           3h34m
client2           True    True     9e981111-9f97-458f-b7fa-736fd5d94572           3h34m
```

**Comment by Breee** [comment]
Greetings,
sorry for the late reply - i had some busy week and no time to answer
I will try to look into that in the evening.

**Comment by Breee** [comment]
Sorry for the radio silence,  i visited kubecon and was on vacation. 

I prepared a fix that enables us to do something like: 

```
apiVersion: openidclient.keycloak.crossplane.io/v1alpha1
kind: ClientServiceAccountRole
metadata:
  name: test-service-account-role
spec:
  forProvider:
    clientIdRef:
      name: test
    realmId: dev
    role: create-realm
    # References the same Client as clientIdRef
    serviceAccountUserClientIdRef:
      name: test
  providerConfigRef:
    name: "keycloak-provider-config"
``` 

I'm no entirely happy with that right now as i would prefer to get rid of 

```
    serviceAccountUserClientIdRef:
      name: test
```

entirely.

Problems: 

**- When generating crossplane providers, i don't know yet how to initialize multiple fields of a ressource based on a single reference, i.e. only clientIdRef  in our case. I'll research on that. 
- The role currently cannot be referenced, as this causes import cycles.  I have to look deeper into that.** 



I'll merge my changes soon tho, then you can test
