### ISSUE TITLE
Unable to reference built-in objects

### ISSUE THREAD

**Issue by daniel-palmer-gu** [crossplane-contrib/provider-keycloak#74]
Is there a way to reference built-in objects other than through a id? It does not appear provider-keycloak provides a good way to reference built-in objects. 

For example, if I want to give a user admin permissions to a realm via a client role on the `realm-management` client, there is no good way of referencing that role. Technically, provider-keycloak can reference it if you go to Keycloak and find the role id. However, that is inconvenient and prevents automating this type of action.

It would be nice if provider-keycloak could be given the role/client role name within Keycloak as a reference. This would be convenient for other built-in objects as well.

It looks like this is something #71 is trying to accomplish as well.

**Comment by daniel-palmer-gu** [comment]
Are there any examples of importing a resource? Not sure I am tracking how to accomplish that.

I think the feature I am looking for are the equivalent of data sources in terraform. For my example, I would want to be able to use a role data source to find the role by name and retrieve the id for use with other resources. https://registry.terraform.io/providers/mrparkers/keycloak/latest/docs/data-sources/role

**Comment by Breee** [comment]
Yeah here:  https://docs.crossplane.io/knowledge-base/guides/import-existing-resources/

**Comment by smoehrle** [comment]
In addition: there is also this open issue for crossplane which might be the feature you're asking for: https://github.com/crossplane/crossplane/issues/4141

**Comment by daniel-palmer-gu** [comment]
So in order to import a client role, I must first know the client id. Unfortunately, I can't import built-in clients as to do so also requires the client id.

For example, if I attempt to import the `realm-management` client on a realm I created called `test-realm`, the client can't be found. Using the following to import the Client:
```yaml
apiVersion: openidclient.keycloak.crossplane.io/v1alpha1
kind: Client
metadata:
  annotations:
    crossplane.io/external-name: test-realm/realm-management
  name: realm-management
spec:
  forProvider: {}
  providerConfigRef:
    name: "non-default-config"
  managementPolicies: ["Observe"]
```

Results in the following status:
```yaml
status:                                                                                                                                                                                        
  atProvider: {}                                                                                                                                                                               
  conditions:                                                                                                                                                                                  
  - lastTransitionTime: "2024-03-11T17:18:19Z"                                                                                                                                                 
    message: "observe failed: cannot run import: \e[0m\e[1mkeycloak_openid_client.realm-management:                                                                                            
      Importing from ID \"test-realm/realm-management\"...\e[0m\n\e[31m\e[31m╷\e[0m\e[0m\n\e[31m│\e[0m                                                                                         
      \e[0m\e[1m\e[31mError: \e[0m\e[0m\e[1merror sending GET request to REDACTED/REDACTED/realms/test-realm/clients/realm-management:                                                         
      404 Not Found. Response body: {\"error\":\"Could not find client\"}\e[0m\n\e[31m│\e[0m                                                                                                   
      \e[0m\n\e[31m│\e[0m \e[0m\e[0m\n\e[31m╵\e[0m\e[0m\n\e[0m\e[0m\n: import failed"                                                                                                          
    reason: ReconcileError                                                                                                                                                                     
    status: "False"                                                                                                                                                                            
    type: Synced 
```

However, If I provide the client id in the import, it works as expected:
```yaml
apiVersion: openidclient.keycloak.crossplane.io/v1alpha1
kind: Client
metadata:
  annotations:
    crossplane.io/external-name: test-realm/75291e36-a704-49a7-b471-a211cf8c2adf
  name: realm-management
spec:
  forProvider: {}
  providerConfigRef:
    name: "non-default-provider"
  managementPolicies: ["Observe"]
```
  
resulting in:
```yaml
status:                                                                                                                                                                                        
  atProvider:                                                                                                                                                                                  
    accessTokenLifespan: ""                                                                                                                                                                    
    accessType: BEARER-ONLY                                                                                                                                                                    
    adminUrl: ""                                                                                                                                                                               
    backchannelLogoutRevokeOfflineSessions: false                                                                                                                                              
    backchannelLogoutSessionRequired: false                                                                                                                                                    
    backchannelLogoutUrl: ""                                                                                                                                                                   
    baseUrl: ""                                                                                                                                                                                
    clientAuthenticatorType: client-secret                                                                                                                                                     
    clientId: realm-management                                                                                                                                                                 
    clientOfflineSessionIdleTimeout: ""                                                                                                                                                        
    clientOfflineSessionMaxLifespan: ""                                                                                                                                                        
    clientSessionIdleTimeout: ""                                                                                                                                                               
    clientSessionMaxLifespan: ""                                                                                                                                                               
    consentRequired: false                                                                                                                                                                     
    consentScreenText: ""                                                                                                                                                                      
    description: ""                                                                                                                                                                            
    directAccessGrantsEnabled: false                                                                                                                                                           
    displayOnConsentScreen: false                                                                                                                                                              
    enabled: true                                                                                                                                                                              
    frontchannelLogoutEnabled: false                                                                                                                                                           
    frontchannelLogoutUrl: ""                                                                                                                                                                  
    fullScopeAllowed: false                                                                                                                                                                    
    id: 75291e36-a704-49a7-b471-a211cf8c2adf                                                                                                                                                   
    implicitFlowEnabled: false                                                                                                                                                                 
    import: false                                                                                                                                                                              
    loginTheme: ""                                                                                                                                                                             
    name: ${client_realm-management}                                                                                                                                                           
    oauth2DeviceAuthorizationGrantEnabled: false                                                                                                                                               
    oauth2DeviceCodeLifespan: ""                                                                                                                                                               
    oauth2DevicePollingInterval: ""                                                                                                                                                            
    realmId: test-realm                                                                                                                                                                        
    rootUrl: ""                                                                                                                                                                                
    serviceAccountUserId: ""                                                                                                                                                                   
    serviceAccountsEnabled: false                                                                                                                                                              
    standardFlowEnabled: true                                                                                                                                                                  
    useRefreshTokens: false                                                                                                                                                                    
    useRefreshTokensClientCredentials: false                                                                                                                                                   
  conditions:                                                                                                                                                                                  
  - lastTransitionTime: "2024-03-11T17:25:03Z"                                                                                                                                                 
    reason: ReconcileSuccess                                                                                                                                                                   
    status: "True"                                                                                                                                                                             
    type: Synced                                                                                                                                                                               
  - lastTransitionTime: "2024-03-11T17:25:04Z"                                                                                                                                                 
    reason: Available                                                                                                                                                                          
    status: "True"                                                                                                                                                                             
    type: Ready 
  ```

**Comment by Breee** [comment]
Hm i guess you need the client-id.

You can extract that when you open your client in keycloak copy it from the URL.  `https://keycloak.example.com/auth/admin/master/console/#/master/clients/707b5c15-bf19-457e-9a7c-9be41f74dda9/settings`   where `707b5c15-bf19-457e-9a7c-9be41f74dda9` would be the id you search.

Can you check if it works for you with the client-id? 

 Sadly that's how keycloak does it. sometimes you reference things by name / sometime you reference it by a uuid. 
would be cool to write a wrapper around that to enable selecting stuff by readable names

**Comment by daniel-palmer-gu** [comment]
If a wrapper seems feasible, that would be awesome.

There are two alternatives I can think of that go outside of provider-keycloak:

1. Using composite functions to lookup the built-in objects (was a suggestion in @smoehrle's linked issue)
1. Importing a realm into Keycloak (via UI or init scripts) which allows the uuid of built-in objects to be known ahead of time
    1. This would mean I am not using provider-keycloak to create/manage the realm when I would prefer to.
    2. This would not be fun to manage if I had to provision and manage many realms

**Comment by QuadmanSWE** [comment]
> Yeah here: https://docs.crossplane.io/knowledge-base/guides/import-existing-resources/ it's important that you set `managementPolicies: ["Observe"]` - else crossplane will rip everything apart if you delete your imported ressources

I tried to create a client with observe managementpolicies but I get this error. I am running crossplane 1.15.1 with provider-keycloak v1.15.0. What did I miss when installing crossplane?

```
`spec.managementPolicies` is set to a non-default value but the feature is not enabled: [Observe]
```

![image](https://github.com/crossplane-contrib/provider-keycloak/assets/8070109/a2e498f8-53b3-438f-b980-47e3b19a2932)


Here is my realm and client by the way, I am trying to create a realm with a default user that is realm admin so that when someone asks for a new realm they can logon once as this user and then let them selves in with federation or something.

Realm shows up and works great, any user I create works too but I can't add realm-admin to them.

```
apiVersion: realm.keycloak.crossplane.io/v1alpha1
kind: Realm
metadata:
  name: developers-realm
spec:
  forProvider:
    realm: developers-realm
    enabled: true
    displayName: "Home of the Developers"
  providerConfigRef:
    name: keycloak-config
---
apiVersion: openidclient.keycloak.crossplane.io/v1alpha1
kind: Client
metadata:
  name: realm-management
spec:
  forProvider:
    realmIdRef: 
      name: developers-realm
  providerConfigRef:
    name: keycloak-config
  managementPolicies: ["Observe"]
```

**Comment by QuadmanSWE** [comment]
To answer my own question, this provider doesn't allow observe by default: https://github.com/crossplane-contrib/provider-keycloak/blob/7d1abb98ad9863effaf74a484e15f63c68e440d6/cmd/provider/main.go#L51

I could enable it by setting this envvar, for example by using a controllerconfig ref in the provider.
```apiVersion: pkg.crossplane.io/v1alpha1
kind: ControllerConfig
metadata:
  name: enable-management-policies-config
spec:
  args:
    - --enable-management-policies 
```
![image](https://github.com/crossplane-contrib/provider-keycloak/assets/8070109/ebcf76d9-c256-4b48-8cb8-aa8b934b0adc)

**Comment by Breee** [comment]
> To answer my own question, this provider doesn't allow observe by default:
> 
> https://github.com/crossplane-contrib/provider-keycloak/blob/7d1abb98ad9863effaf74a484e15f63c68e440d6/cmd/provider/main.go#L51
> 
> I could enable it by setting this envvar, for example by using a controllerconfig ref in the provider.
> 
> ```
> kind: ControllerConfig
> metadata:
>   name: enable-management-policies-config
> spec:
>   args:
>     - --enable-management-policies 
> ```
> 
> ![image](https://private-user-images.githubusercontent.com/8070109/323233856-ebcf76d9-c256-4b48-8cb8-aa8b934b0adc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM0MjI1MjgsIm5iZiI6MTcxMzQyMjIyOCwicGF0aCI6Ii84MDcwMTA5LzMyMzIzMzg1Ni1lYmNmNzZkOS1jMjU2LTRiNDgtOGNiOC1hYThiOTM0YjBhZGMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQxOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MThUMDYzNzA4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MDA0OWNiOGE2NjdmMDFmODMzYzI5YWEyNWQ2MmRlZWMxMmJkMWY5MTY3MDFlZWQ5MTY0NTRlZjlkNzQwZTZlMyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.fORMsSOeCAkolcQ-LkvfM3YhX29_7Fl23tjefsoIOcc)

In release v0.16.0  management policies are now enabled by default - i think this makes sense for this provider

**Comment by vladimirblahoz** [comment]
Right now I am trying to attempt the exactly same thing - assign realm-management client roles to my service account. And if I understood correctly to achieve that I need:

- the existing realm-management client imported into crossplane so that I can properly target the ClientServiceAccountRole towards the client using `clientIdSelector`, or directly through `clientId` obtaining that from that imported client resource.
- To be able to do that, I need to have the very same realm-management client's ID (meaning the non-human-readable UUID) to be able to import an existing keycloak resource using `crossplane.io/external-name` annotation and `managementPolicies: [ "Observe" ]`

Meaning the chicken-egg problem is real. I am really in a need to be able to automate everything, so looking up the built-in client's ID through the keycloak UI is a no-go and this starts to be quite problematic for me.

**Comment by Breee** [comment]
I agree, how the keycloak API / backend currently works is problematic for our usecases. 
There is two approaches that come to my mind: 
- a) We write a composition / compositon function that  deploys the and fetches the builtin roles from keycloak using: 
   1. https://docs.crossplane.io/knowledge-base/guides/write-a-composition-function-in-python/ or https://docs.crossplane.io/knowledge-base/guides/write-a-composition-function-in-go/  
   2. Fetch builtin roles -> generate these roles as Role objects such that they are referenceable.
- b) We somehow integrate this wrapper into the provider code (I need to do more research on how to overwrite the generated code by upjet)

**Comment by Breee** [comment]
Ok guys, i made a poc:  https://gitlab.com/corewire/images/crossplane/function-keycloak-builtin-clients which calls a composition function: https://gitlab.com/corewire/images/crossplane/function-keycloak-builtin-clients/-/blob/main/function/fn.py?ref_type=heads#L40 

1. XRD: 
```
apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xbuiltinclients.crossplane.corewire.io  # required to be in the format <plural>.<group>
spec:
  group: crossplane.corewire.io
  names:
    kind: XBuiltinClients
    plural: xbuiltinclients
  versions:
  - name: v1alpha1
    served: true
    referenceable: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              realm:
                type: string
              provider_config_name:
                type: string
              url: 
                type: string
              username:
                type: string
              password:
                type: string
            required:
            - realm
            - provider_config_name
            - url
            - username
            - password
        required:
        - spec
```
2.  Composition:
```
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: keycloak-builtin-clients
spec:
  compositeTypeRef:
    apiVersion: crossplane.corewire.io/v1alpha1
    kind: XBuiltinClients
  mode: Pipeline
  pipeline:
  - step: keycloak-builtin-clients
    functionRef:
      name: function-keycloak-builtin-clients
```
3. Function
```
---
apiVersion: pkg.crossplane.io/v1beta1
kind: Function
metadata:
  name: function-keycloak-builtin-clients
  #annotations:
  #  # This tells crossplane beta render to connect to the function locally.
  #  render.crossplane.io/runtime: Development
spec:
  # This is ignored when using the Development runtime.
  package: registry.gitlab.com/corewire/images/crossplane/function-keycloak-builtin-clients:v1.0.6
  packagePullPolicy: Always
```
4. XR
```
apiVersion: crossplane.corewire.io/v1alpha1
kind: XBuiltinClients
metadata:
  name: keycloak-builtin-clients
spec:
  realm: master
  provider_config_name: keycloak-provider-config
  url: http://172.25.0.31:80/auth/
  username: admin
  password: admin
```

That generates me the clients: 

```
$ k get clients
NAME                     READY   SYNCED   EXTERNAL-NAME                                 AGE
account                  True    True     master/d0721a8e-9b57-4b9e-ab1c-8122184fe932   6m9s
account-console          True    True     master/7288704c-dd24-486d-bf4b-c0d375075940   6m9s
admin-cli                True    True     master/47f56720-63fe-4270-8c50-9d6255a15c1c   6m9s
broker                   True    True     master/290085fe-f831-4eaa-bff3-4016923a2f3b   6m9s
master-realm             True    True     master/8ce939fe-01fd-4b3c-91ed-78d439a55f85   6m9s
security-admin-console   True    True     master/789bd109-35c5-42c3-9525-5e52f037e220   6m9s
``` 

**Obviously this is not Production ready, as i for simplicity just passed in everything the function need to talk to keycloak **  

Would something like that be okay for you to use?  
Of course prettified / enhanced  - as this just gets all current clients of a keycloak instance and imports them using external names. Optimally we just pass a list of builtin clients we want.  

lmk and i'll provide something
