### ISSUE TITLE
Unable to set realm default roles

### ISSUE THREAD

**Issue by vladimirblahoz** [crossplane-contrib/provider-keycloak#80]
Hi!
Is there any example of how to set default roles for crossplane managed realm? 
I have a keycloak v 24.0.2 deployed and a realm provisioned by keycloak-provider v 0.15.0. When this realm is created, it automatically creates a composite role named "default-roles-[realm-name]" into which I need to assign my default roles. Obviously the default-roles role is not managed by crossplane.
I assumed looking at its name that the resource [defaults.keycloak.crossplane.io/v1alpha1/roles](https://marketplace.upbound.io/providers/crossplane-contrib/provider-keycloak/v0.15.0/resources/defaults.keycloak.crossplane.io/Roles/v1alpha1) is meant for this.

`apiVersion: defaults.keycloak.crossplane.io/v1alpha1
kind: Roles
metadata:
  name: default-roles
spec:
  forProvider:
    realmId: testrealm
    defaultRolesRefs:
      - name: default
  providerConfigRef:
    name: keycloak-provider-config
`

Applying this manifest results in quite strange error event:

<img width="1482" alt="image" src="https://github.com/crossplane-contrib/provider-keycloak/assets/104296051/43078450-9439-481f-99e7-888abfbbf910">

I also tried another approach based on [Import Existing Resource](https://docs.crossplane.io/knowledge-base/guides/import-existing-resources/) documentation and importing the automatically created role with:

`apiVersion: role.keycloak.crossplane.io/v1alpha1
kind: Role
metadata:
  name: imported-default-roles
  annotations:
    crossplane.io/external-name: default-roles-testrealm
spec:
  forProvider:
    realmId: testrealm
    name: default-roles-testrealm
    compositeRolesRefs:
      - name: default
  providerConfigRef:
    name: keycloak-provider-config
`

That fails on an attempt to newly create the existing role resulting in names conflict
<img width="1468" alt="image" src="https://github.com/crossplane-contrib/provider-keycloak/assets/104296051/a4ad847a-6e70-47f2-996e-3872982042f7">

I also tried just to test the importing works to add `managementPolicies: [ "Observe" ]` to the role manifest (being aware that with that I shouldn't be able to change the compositeRolesRefs) and that again fails on another error

<img width="1455" alt="image" src="https://github.com/crossplane-contrib/provider-keycloak/assets/104296051/ba0acc1d-154e-4beb-9d8e-a6a4a3bde3aa">

This makes me feel that keycloak provider does not support the managementPolicies. And I am kind of out of ideas.
Any help will be very appreciated.

**Comment by QuadmanSWE** [comment]
I ran into this just now, link to the findings. You can enable this but it will not help you to find the default realm role since you need to reference its external name by some random guid.

https://github.com/crossplane-contrib/provider-keycloak/issues/74#issuecomment-2061253814

**Comment by QuadmanSWE** [comment]
Even when importing the client and the roles from their random guids in keycloak to crossplane I was unable to actually make a user an admin. I tried to grant the role directly but I couldn't find what resource to use for that but then I found group roles but that apparently doesn't do anything. Membership worked fine and my user becomes member of my "realm-admin" group but the group doesn't get the proper role eventhough the roleidref seems to work fine?

![image](https://github.com/crossplane-contrib/provider-keycloak/assets/8070109/06383c89-1212-4f28-ab64-c2771fc985ac)

Here is my entire attempt:
```
apiVersion: realm.keycloak.crossplane.io/v1alpha1
kind: Realm
metadata:
  name: developers-realm
spec:
  forProvider:
    realm: developers-realm
    enabled: true
    displayName: "Home of the Developers"
  providerConfigRef:
    name: keycloak-config
---
apiVersion: openidclient.keycloak.crossplane.io/v1alpha1
kind: Client
metadata:
  name: realm-management-developers-realm
  annotations: 
    crossplane.io/external-name: developers-realm/0f84dce2-76b2-49ac-ba2e-681a604c78b7
spec:
  forProvider: {}
  providerConfigRef:
    name: keycloak-config
  managementPolicies: ["Observe"]
---
apiVersion: role.keycloak.crossplane.io/v1alpha1
kind: Role
metadata:
  name: manage-realm-realm-management-developers-realm
  annotations: 
    crossplane.io/external-name: developers-realm/0acc58b1-3eb0-4ec1-9979-7a97fc10a89b
spec:
  forProvider: {}
  providerConfigRef:
    name: keycloak-config
  managementPolicies: ["Observe"]
---
apiVersion: group.keycloak.crossplane.io/v1alpha1
kind: Group
metadata:
  name: developers-realm-admins
spec:
  forProvider:
    realmIdRef:
      name: developers-realm
    name: realm-admins
  providerConfigRef:
    name: keycloak-config
---
apiVersion: group.keycloak.crossplane.io/v1alpha1
kind: Roles
metadata:
  name: developers-realm-admins-roles
spec:
  forProvider:
    groupIdRef:
      name: developers-realm-admins
      policy:
        resolution: Required
    realmIdRef:
      name: developers-realm
      policy:
        resolution: Required
    roleIdsRefs:
      - name: manage-realm-realm-management-developers-realm
        policy:
          resolution: Required
  providerConfigRef:
    name: keycloak-config
---
apiVersion: group.keycloak.crossplane.io/v1alpha1
kind: Memberships
metadata:
  name: developers-realm-admins-memberships
spec:
  forProvider:
    groupIdRef:
      name: developers-realm-admins
    members:
      - guest
    realmIdRef:
      name: developers-realm
  providerConfigRef:
    name: keycloak-config
---
apiVersion: user.keycloak.crossplane.io/v1alpha1
kind: User
metadata:
  name: guest-user-developers-realm
spec:
  forProvider:
    realmIdRef:
      name: developers-realm
    username: "guest"
    email: "guest@somedomain.com"
    firstName: "Guest"
    lastName: "User"
    emailVerified: true
    initialPassword:
      - temporary: true
        valueSecretRef:
          key: default-password
          name: default-user-settings
          namespace: development
    requiredActions: # VERIFY_EMAIL, UPDATE_PROFILE, CONFIGURE_TOTP, UPDATE_PASSWORD, TERMS_AND_CONDITIONS
      - UPDATE_PROFILE
      - CONFIGURE_TOTP
  providerConfigRef:
    name: keycloak-config
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: default-user-settings
  namespace: development
spec:
  encryptedData:
    default-password: someencryptedpassword
  template:
    metadata:
      creationTimestamp: null
      name: default-user-settings
      namespace: development
    type: Opaque
```

**Comment by mustafa-be** [comment]
Hello @QuadmanSWE , I had the same issue a while ago, I was able to make the default roles resource work by setting an appropriate ExternalNameConfig in [config/external_name.go](https://github.com/crossplane-contrib/provider-keycloak/blame/e797c55e9c3ff4612815bdfed1d392d096e5407f/config/external_name.go#L43)

You would be able to set default realm roles using this resource eg https://github.com/crossplane-contrib/provider-keycloak/blob/main/examples-generated/defaults/v1alpha1/roles.yaml

Problem with this resource is that you wouldnt be able to set default roles of a client because its not supported in upstream tf provider, Theres a pull request for it [terraform-provider-keycloak](https://github.com/crossplane-contrib/provider-keycloak/issues/80) repository thats waiting to be merged for a long time.

**Comment by mustafa-be** [comment]
I did have an alternative for it, but it might not be the best. We already have [ansible provider](https://marketplace.upbound.io/providers/crossplane-contrib/provider-ansible/v0.3.0/resources/ansible.crossplane.io/AnsibleRun/v1alpha1) on our clusters.

I simply used an AnsibleRun to configure default roles and it worked, The community general collection has module for keycloak API. This helped resolve my issue specifically https://docs.ansible.com/ansible/latest/collections/community/general/keycloak_role_module.html#ansible-collections-community-general-keycloak-role-module. 

Obviously its way better to have it included in provider.

**Comment by Breee** [comment]
mustafa means this PR https://github.com/mrparkers/terraform-provider-keycloak/pull/764

**Comment by Breee** [comment]
Alright guys, the default roles are kinda trashy and we have no choice than writing our own controller for that. 

I however found a good workaround for you which is in my opinion even better to manage. PR  https://github.com/crossplane-contrib/provider-keycloak/pull/86  adds `default_groups` 

Full Example with realm + client roles:

```
---
apiVersion: realm.keycloak.crossplane.io/v1alpha1
kind: Realm
metadata:
  name: my-realm
spec:
  forProvider:
    enabled: true
    realm: my-realm
  providerConfigRef:
    name: keycloak-provider-config
---
apiVersion: openidclient.keycloak.crossplane.io/v1alpha1
kind: Client
metadata:
  name: test
spec:
  forProvider:
    realmIdRef:
      name: "my-realm"
    accessType: "CONFIDENTIAL"
    clientId: "test"
    serviceAccountsEnabled: false
  providerConfigRef:
    name: "keycloak-provider-config"
---
apiVersion: role.keycloak.crossplane.io/v1alpha1
kind: Role
metadata:
  name: my-realm-role
spec:
  forProvider:
    description: My Realm Role
    name: my-realm-role
    realmIdRef:
      name: my-realm
  providerConfigRef:
    name: keycloak-provider-config
---apiVersion: defaults.keycloak.crossplane.io/v1alpha1
kind: DefaultGroups
metadata:
  annotations:
    meta.upbound.io/example-id: defaults/v1alpha1/defaultgroups
  labels:
    testing.upbound.io/example-name: default
  name: default
spec:
  forProvider:
    groupIdsRefs:
    - name: group
    realmIdSelector:
      matchLabels:
        testing.upbound.io/example-name: realm
---

apiVersion: group.keycloak.crossplane.io/v1alpha1
kind: Group
metadata:
  annotations:
    meta.upbound.io/example-id: defaults/v1alpha1/defaultgroups
  labels:
    testing.upbound.io/example-name: group
  name: group
spec:
  forProvider:
    name: my-group
    realmIdSelector:
      matchLabels:
        testing.upbound.io/example-name: realm

---

apiVersion: realm.keycloak.crossplane.io/v1alpha1
kind: Realm
metadata:
  annotations:
    meta.upbound.io/example-id: defaults/v1alpha1/defaultgroups
  labels:
    testing.upbound.io/example-name: realm
  name: realm
spec:
  forProvider:
    enabled: true
    realm: my-realm
apiVersion: role.keycloak.crossplane.io/v1alpha1
kind: Role
metadata:
  name: my-client-role
spec:
  forProvider:
    description: My Client Role
    name: my-client-role
    realmIdRef:
      name: my-realm
    clientIdRef:
      name: test
  providerConfigRef:
    name: keycloak-provider-config
---
apiVersion: group.keycloak.crossplane.io/v1alpha1
kind: Group
metadata:
  name: my-group
spec:
  forProvider:
    name: my-group
    realmIdRef:
      name: my-realm
  providerConfigRef:
    name: keycloak-provider-config
--- 
# Example Role mapping: Using groupId and roleIds to assign roles to the default group
apiVersion: group.keycloak.crossplane.io/v1alpha1
kind: Roles
metadata:
  name: dev-group-roles
spec:
  forProvider:
    realmIdRef:
      name: my-realm
    groupIdRef: 
      name: my-group
    roleIdsRefs:
      - name: my-realm-role
      - name: my-client-role
  providerConfigRef:
    name: keycloak-provider-config
--- 
apiVersion: defaults.keycloak.crossplane.io/v1alpha1
kind: DefaultGroups
metadata:
  name: default
spec:
  forProvider:
    groupIdsRefs:
    - name: my-group
    realmIdRef:
      name: my-realm
  providerConfigRef:
    name: keycloak-provider-config
```

I hope that helps you out until the controller is ready to roll. 

You can test that out in version v0.18.0 

https://marketplace.upbound.io/providers/crossplane-contrib/provider-keycloak/v0.18.0

**Comment by b509** [comment]
Hey @vladimirblahoz,
I needed this exact same feature and added it to @Breee's thankfully provided crossplane function. If you want to have a look at it, maybe it helps
https://gitlab.com/corewire/images/crossplane/function-keycloak-builtin-objects#5-modified-default-config

(For a general documentation on how to make the function run, read the complete README)

**Comment by michvllni** [comment]
@Breee I am aware of this, but the creation of compound roles consisting of default client roles still isn't working. I am getting the same error as in terraform.

That is why I asked why we can't do it directly like in terraform as it seems to work there.

So, in crossplane, the example from above would look like this:
```yml
apiVersion: openidclient.keycloak.m.crossplane.io/v1alpha1
kind: Client
metadata:
  name: example-realm-management-test
  namespace: keycloak
spec:
  managementPolicies: ["Observe"]
  forProvider:
    realmIdRef:
      name: example
    import: true

    # Client configuration
    clientId: realm-management
---
apiVersion: role.keycloak.m.crossplane.io/v1alpha1
kind: Role
metadata:
  name: test-example-user-manage
  namespace: keycloak
spec:
  managementPolicies: ["Observe", "LateInitialize"]
  forProvider:
    clientIdRef:
      name: example-realm-management-test
      namespace: keycloak
    import: true
    name: manage-users
    realmIdRef:
      name: example
---
apiVersion: role.keycloak.m.crossplane.io/v1alpha1
kind: Role
metadata:
  name: test-compoosite-role
  namespace: keycloak
spec:
  forProvider:
    name: test-user-admin-composite
    description: "Composite role for user administration across all realms"
    compositeRolesRefs:
      - name: test-example-user-manage
        namespace: keycloak
    realmIdRef:
      name: example
```

From what I've discovered in the terraform state, the UUID is actually part of the client resource, and `keycloak_client.realm_management.id` yields the UUID:
```json
{
      "mode": "managed",
      "type": "keycloak_openid_client",
      "name": "realm_management",
      "provider": "provider[\"registry.terraform.io/keycloak/keycloak\"]",
      "instances": [
        {
          "schema_version": 0,
          "attributes": {
            ...
            "client_id": "realm-management",
            ...
            "id": "d7e49870-b73a-4190-b0a6-2f37c568f2c3",
            ...
          },
         ...
        }
      ]
    }
```

```hcl
output "client_uuid" {
  value = keycloak_openid_client.realm_management.id
}

output "client_id" {
  value = keycloak_openid_client.realm_management.client_id
}
```
```
Changes to Outputs:
  + client_id   = "realm-management"
  + client_uuid = "d7e49870-b73a-4190-b0a6-2f37c568f2c3"
```

That is where my question originates from.

**Comment by michvllni** [comment]
@Breee I have opened #447 to solve the issue with client roles in compositeRoleRefs. I tested it in my cluster and it worked. Would you mind taking a look?

**Comment by eshepelyuk** [comment]
Hello, it's still not working for 2.19.0

I'm having client and client role declared and they are succesfully created.

```yaml
apiVersion: role.keycloak.crossplane.io/v1alpha1
kind: Role
metadata:
  name: dashboard-role-gamma
spec:
  forProvider:
    clientIdRef:
      name: dashboard-superset
    name: Gamma
    realmId: test
```
In case I use both `defaultRoles` and `defaultRolesRef` - only `defaultRoles` are taken into consideration.

```yaml
apiVersion: defaults.keycloak.crossplane.io/v1alpha1
kind: Roles
metadata:
  name: dashboard-default-role
spec:
  forProvider:
    defaultRoles:
    - offline_access
    - uma_authorization
    defaultRolesRefs:
    - name: dashboard-role-gamma
    realmId: test
```

In case I use only `defaultRolesRef` - the provider tries to resolve realm role, not client one, i.e. i see 404 in `.status`

```yaml
apiVersion: defaults.keycloak.crossplane.io/v1alpha1
kind: Roles
metadata:
  name: dashboard-default-role
spec:
  forProvider:
    defaultRolesRefs:
    - name: dashboard-role-gamma
    realmId: test
```
Error from `.status`

```
  - lastTransitionTime: "2026-05-14T10:26:09Z"
    message: 'update failed: async update failed: failed to update the resource: [{0 error sending GET request to /admin/realms/test/roles/Gamma: 404 Not Found. Response body: {"error":"Could not find role"}  []}]'
    reason: ReconcileError
    status: "False"
    type: Synced
